name: Hash of last commit 

on: 
  push 
jobs:
  thisOne: 
    runs-on: macos-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: |
          input="./generate_postmortem.sh"
          COMM=`git rev-parse HEAD`
          CURRENTCOMMIT="PMVERSION='$COMM'"
          sed -i -e "s|PMVERSION=.*|$CURRENTCOMMIT|g" ${GITHUB_WORKSPACE}/file.sh
          git config --global user.name "actionbot"
          git config --global user.email "githubactions" 
          git commit -a -m "Automatic update of version"
          git push
          
        shell: bash
